import type { Metadata } from 'next'
import { Sawarabi_Gothic } from 'next/font/google'
import './globals.css'

const sawarabiGothic = Sawarabi_Gothic({weight: '400', subsets: ['cyrillic']})

export const metadata: Metadata = {
  title: 'Home page',
  applicationName: 'My portfolio',
  keywords: ['next.js', 'react', 'tailwind', 'typescript'],
  creator: 'Haixu Jin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sawarabiGothic.className}>{children}</body>
    </html>
  )
}
